export * from './condition';
export * from './result.interface';
export * from './user.interface';
export * from './device.interface';
export * from './credentials.interface';
export * from './company.interface';
export * from './profile.interface';
export * from './search-filters.interface';
export * from './pokedex.interface';